version: 2

jobs:
  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: yarn --no-progress
      - run: yarn build
      - run: yarn flow
      - run: yarn test-ci
      - run: yarn lint
  build_and_deploy:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "21:2b:e9:22:ad:4c:d8:53:7c:5d:b4:84:80:8d:a2:2e"
      - checkout
      - run: yarn --no-progress
      - run: yarn build
      - run: yarn flow
      - run: yarn test-ci
      - run: yarn lint
      - run: node ./scripts/deploy.js


workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore: master 
      - build_and_deploy:
          filters:
            branches:
              only: master